name: Deploy to Production

on:
  push:
    branches:
      - lef
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-spring-boot-app:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-spring-boot-app:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to production server
        run: |
          ssh your_user@your_server << 'EOF'
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-spring-boot-app:latest
            docker stop my-spring-boot-app || true
            docker rm my-spring-boot-app || true
            docker run -d --name my-spring-boot-app -p 80:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/my-spring-boot-app:latest
          EOF